YOSYS ?= yosys
EQY ?= eqy
VERILATOR ?= verilator
NAJA_EDIT ?= ../../../../../install/bin/naja_edit
PRIMITIVES ?= ../../../../../primitives/xilinx.py 
ASAP7_PRIMITIVES ?= $(realpath ../../../primitives/asap7.py) 
NANGATE45_PRIMITIVES ?= $(realpath ../../../primitives/nangate45.py) 
SET_PYTHONPATH ?= ../../../../../install/lib/python
