YOSYS ?= yosys
EQY ?= eqy
VERILATOR ?= verilator
NAJA_EDIT ?= $(realpath ../../build/src/apps/edit/naja_edit)
PRIMITIVES ?= $(realpath ../../primitives/xilinx.py) 
ASAP7_PRIMITIVES ?= $(realpath ../../primitives/asap7.py) 
NANGATE45_PRIMITIVES ?= $(realpath ../../primitives/nangate45.py) 
SET_PYTHONPATH ?= $(realpath ../../build/src/snl/python/snl_wrapping)
