YOSYS ?= yosys
EQY ?= eqy
VERILATOR ?= verilator
NAJA_EDIT ?= $(realpath ../../build/src/apps/edit/naja_edit)
PRIMITIVES ?= $(realpath ../../primitives/xilinx.py) 
SET_PYTHONPATH ?= $(realpath ../../build/src/snl/python/snl_wrapping)
