# SPDX-FileCopyrightText: 2026 The Naja authors <https://github.com/najaeda/naja/blob/main/AUTHORS>
#
# SPDX-License-Identifier: Apache-2.0

cc_library(
    name = "naja_snl_xls_ir",
    srcs = ["frontend/SNLXLSConstructor.cpp"],
    hdrs = [
        "frontend/SNLXLSConstructor.h",
        "frontend/SNLXLSConstructorException.h",
    ],
    includes = ["frontend"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/nl/formats/common:naja_nl_frontend_common",
        "//src/nl/netlist:naja_nl",
    ],
)
