// SPDX-FileCopyrightText: 2026 The Naja authors <https://github.com/najaeda/naja/blob/main/AUTHORS>
//
// SPDX-License-Identifier: Apache-2.0

`timescale 1ns/1ps
`include "axi/typedef.svh"
`include "axi/assign.svh"

// Functional-equivalence smoke test for the Naja-generated axi_cut_top netlist.
//
// Note on axi_test.sv VIP compatibility:
//   axi_rand_master / axi_rand_slave use `wait (class_member.size() > 0)` to
//   coordinate their internal queues across concurrent fork tasks.  Verilator
//   --timing only re-evaluates `wait` on logic/wire signal changes, NOT on
//   class-member mutations, so those tasks block forever.  A commercial
//   simulator (ModelSim/Questasim/VCS) is needed to run the full VIP.
//
// What this testbench does instead:
//   Drives 256 back-to-back AXI write + read bursts using the official
//   axi/typedef.svh-generated types so the struct↔flat-port mapping is
//   identical to a real integration.  The memory model returns
//   {ar.addr, ~ar.addr} as read data — each of the 256 R responses carries a
//   unique, address-derived 64-bit value that is verified on receipt.

module tb_axi_cut_smoke;

  // ------------------------------------------------------------------ //
  // AXI types — generated by AXI_TYPEDEF_ALL exactly as in              //
  // axi_cut_top_pkg so the packed-struct bit layout matches the DUT.    //
  // ------------------------------------------------------------------ //
  localparam int unsigned AXI_AW = 32;
  localparam int unsigned AXI_DW = 64;
  localparam int unsigned AXI_IW = 8;
  localparam int unsigned AXI_UW = 1;

  typedef logic [AXI_AW-1:0]   addr_t;
  typedef logic [AXI_DW-1:0]   data_t;
  typedef logic [AXI_DW/8-1:0] strb_t;
  typedef logic [AXI_IW-1:0]   id_t;
  typedef logic [AXI_UW-1:0]   user_t;
  `AXI_TYPEDEF_ALL(axi, addr_t, id_t, data_t, strb_t, user_t)

  localparam int unsigned NumTransactions = 256;
  localparam int unsigned TimeoutCycles   = 600;
  localparam addr_t WR_BASE = 32'h1000_0000;
  localparam addr_t RD_BASE = 32'h2000_0000;

  logic  clk, rst_n;
  axi_req_t  slv_req;
  axi_resp_t slv_resp;
  axi_req_t  mst_req;
  axi_resp_t mst_resp;

  int unsigned cycle_count;
  int unsigned wr_sent, rd_sent;
  int unsigned wr_done, rd_done;

  // ------------------------------------------------------------------ //
  // Clock & reset                                                        //
  // ------------------------------------------------------------------ //
  initial clk = '0;
  always  #5 clk = ~clk;

  initial begin
    rst_n = '0;
    repeat (4) @(posedge clk);
    @(negedge clk) rst_n = '1;
  end

  // ------------------------------------------------------------------ //
  // Combinatorial memory model on master port                           //
  // Always-ready; returns {ar.addr, ~ar.addr} as read data for each R. //
  // ------------------------------------------------------------------ //
  always_comb begin
    mst_resp          = '0;
    mst_resp.aw_ready = 1'b1;
    mst_resp.w_ready  = 1'b1;
    mst_resp.ar_ready = 1'b1;
    if (mst_req.aw_valid && mst_req.w_valid) begin
      mst_resp.b_valid = 1'b1;
      mst_resp.b.resp  = 2'b00;
      mst_resp.b.id    = mst_req.aw.id;
    end
    if (mst_req.ar_valid) begin
      mst_resp.r_valid = 1'b1;
      mst_resp.r.data  = data_t'({mst_req.ar.addr, ~mst_req.ar.addr});
      mst_resp.r.resp  = 2'b00;
      mst_resp.r.last  = 1'b1;
      mst_resp.r.id    = mst_req.ar.id;
    end
  end

  // ------------------------------------------------------------------ //
  // Combinatorial slave driver — keep valid until handshake             //
  // ------------------------------------------------------------------ //
  always_comb begin
    slv_req         = '0;
    slv_req.b_ready = 1'b1;
    slv_req.r_ready = 1'b1;
    if (wr_sent < NumTransactions) begin
      slv_req.aw_valid = 1'b1;
      slv_req.aw.addr  = WR_BASE + addr_t'(wr_sent) * 8;
      slv_req.aw.burst = 2'b01;
      slv_req.aw.size  = 3'b011;
      slv_req.w_valid  = 1'b1;
      slv_req.w.data   = data_t'({wr_sent[31:0], ~wr_sent[31:0]});
      slv_req.w.strb   = 8'hFF;
      slv_req.w.last   = 1'b1;
    end
    if (rd_sent < NumTransactions) begin
      slv_req.ar_valid = 1'b1;
      slv_req.ar.addr  = RD_BASE + addr_t'(rd_sent) * 8;
      slv_req.ar.burst = 2'b01;
      slv_req.ar.size  = 3'b011;
    end
  end

  // ------------------------------------------------------------------ //
  // State tracking and response verification                             //
  // ------------------------------------------------------------------ //
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      cycle_count <= '0;
      wr_sent <= '0;  rd_sent <= '0;
      wr_done <= '0;  rd_done <= '0;
    end else begin
      cycle_count <= cycle_count + 1;

      if (slv_req.aw_valid && slv_resp.aw_ready) wr_sent <= wr_sent + 1;
      if (slv_req.ar_valid && slv_resp.ar_ready) rd_sent <= rd_sent + 1;

      if (slv_resp.b_valid && slv_req.b_ready) begin
        if (slv_resp.b.resp !== 2'b00)
          $fatal(1, "AXI_CUT_SMOKE_BAD_BRESP resp=%02b txn=%0d",
                 slv_resp.b.resp, wr_done);
        wr_done <= wr_done + 1;
      end

      if (slv_resp.r_valid && slv_req.r_ready && slv_resp.r.last) begin
        begin
          automatic addr_t exp_addr = RD_BASE + addr_t'(rd_done) * 8;
          automatic data_t exp_data = data_t'({exp_addr, ~exp_addr});
          if (slv_resp.r.resp !== 2'b00)
            $fatal(1, "AXI_CUT_SMOKE_BAD_RRESP resp=%02b txn=%0d",
                   slv_resp.r.resp, rd_done);
          if (slv_resp.r.data !== exp_data)
            $fatal(1, "AXI_CUT_SMOKE_BAD_RDATA got=%h exp=%h txn=%0d",
                   slv_resp.r.data, exp_data, rd_done);
        end
        rd_done <= rd_done + 1;
      end

      if (wr_done >= NumTransactions && rd_done >= NumTransactions) begin
        $display("AXI_CUT_SMOKE_PASS cycles=%0d wr=%0d rd=%0d",
                 cycle_count, wr_done, rd_done);
        $finish;
      end
      if (cycle_count >= TimeoutCycles)
        $fatal(1, "AXI_CUT_SMOKE_TIMEOUT wr_done=%0d rd_done=%0d",
               wr_done, rd_done);
    end
  end

  // ------------------------------------------------------------------ //
  // DUT                                                                  //
  // ------------------------------------------------------------------ //
  axi_cut_top dut (
    .clk_i     (clk),
    .rst_ni    (rst_n),
    .slv_req_i (slv_req),
    .slv_resp_o(slv_resp),
    .mst_req_o (mst_req),
    .mst_resp_i(mst_resp)
  );
endmodule
