# SPDX-FileCopyrightText: 2026 The Naja authors <https://github.com/najaeda/naja/blob/main/AUTHORS>
#
# SPDX-License-Identifier: Apache-2.0

cc_test(
    name = "snlXLSConstructorTests",
    srcs = ["SNLXLSConstructorTest.cpp"],
    deps = [
        "//src/nl/formats/xls_ir:naja_xls_ir_bridge_capnp",
        "//src/nl/formats/xls_ir:naja_snl_xls_ir",
        "@googletest//:gtest_main",
    ],
)
