name: coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug
  LLVM_PROFILE_FILE: coverage-%p.profraw

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yq \
          clang llvm \
          libboost-dev libfl-dev \
          capnproto libcapnp-dev \
          libtbb-dev

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DCODE_COVERAGE=ON \
          -DLONG_TESTS=ON

    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build \
          -j $(nproc) \
          --config ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -VV -C ${{ env.BUILD_TYPE }}

    - name: Generate coverage
      working-directory: ${{ github.workspace }}/build
      run: |
        llvm-profdata merge -sparse coverage-*.profraw -o coverage.profdata

        BINARIES=$(find . -type f -executable \
          ! -path './CMakeFiles/*' \
          ! -path './_deps/*')

        llvm-cov export \
          $BINARIES \
          -instr-profile=coverage.profdata \
          -format=lcov \
          -ignore-filename-regex='/usr/|/test/|/build/|/thirdparty/|/src/apps/|/src/app_snippet/|/src/nl/formats/lefdef/|/src/nl/snippets/' \
          > coverage.info

        llvm-cov report \
          $BINARIES \
          -instr-profile=coverage.profdata \
          -ignore-filename-regex='/usr/|/test/|/build/|/thirdparty/|/src/apps/|/src/app_snippet/|/src/nl/formats/lefdef/|/src/nl/snippets/'

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v6
      with:
        fail_ci_if_error: true
        files: ${{ github.workspace }}/build/coverage.info
        disable_search: true
        flags: unittests
        name: codecov-umbrella
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}