name: Emscripten Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      # install dependencies
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -yq libfl-dev

      - name: get boost
        run: |
          wget https://archives.boost.io/release/1.89.0/source/boost_1_89_0.tar.gz
          tar -xzf boost_1_89_0.tar.gz

      - name: Copy locally FlexLexer.h
        run: mkdir -p flex_include && cp /usr/include/FlexLexer.h flex_include

      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Configure (Emscripten)
        run: |
          emcmake cmake -S . -B build-wasm \
              -DBUILD_EMSCRIPTEN=ON \
              -DCMAKE_BUILD_TYPE=Release \
              -DFLEX_INCLUDE_DIR=$(pwd)/flex_includes \
              -DBOOST_ROOT=$(pwd)/boost_1_89_0 \
              -DBoost_NO_SYSTEM_PATHS=ON \
              -DBoost_INCLUDE_DIR=$(pwd)/boost_1_89_0/include \
              -DBoost_NO_BOOST_CMAKE=ON

      - name: Build
        run: cmake --build build-wasm -j

      - name: Run tests
        working-directory: build-wasm
        run: ctest
