name: regress

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release
  NAJA_INSTALL: ${{ github.workspace }}/naja-install

jobs:
  regress:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -yq libboost-dev libfl-dev capnproto libcapnp-dev libtbb-dev rsync

    - name: Configure
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.NAJA_INSTALL }} -DENABLE_SANITIZERS=OFF

    - name: Build and install
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} -j$(nproc) && cmake --install ${{ github.workspace }}/build

    - name: Run megaboom regress
      run: make -C ${{ github.workspace }}/regress/designs/verilog/megaboom
      env:
        NAJA_INSTALL: ${{ env.NAJA_INSTALL }}
