name: tutorials regression

on:
  push:
    branches:
      - main
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        submodules: true

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yq libboost-dev libfl-dev capnproto libcapnp-dev libtbb-dev graphviz

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_SANITIZERS=OFF -DLONG_TESTS=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'

    - name: Install Python dependencies
      run: pip install nbmake nbstripout pandas matplotlib

    - name: Strip notebook outputs before execution
      run: nbstripout tutorials/notebooks/*.ipynb

    - name: Run tutorials
      env:
        PYTHONPATH: ${{github.workspace}}/build/test/najaeda
        NAJAEDA_TUTORIALS_BENCHMARKS: ${{github.workspace}}/tutorials/benchmarks
      run: pytest --nbmake tutorials/notebooks/
